### ISSUE TITLE
XBlock is broken

### ISSUE THREAD

**Issue by shadinaif** [openedx/AnimationXBlock#87]
Looks like this XBlock is not being used. I've opened this PR as part of a translation project [FC-0012](https://openedx.atlassian.net/l/cp/XGS0iCcQ)

I'm testing on Devstack-palm

* The XBlock display name in studio is showing Completion instead of Animation, which give the scenes that the XBlock is not being used. See https://github.com/openedx/AnimationXBlock/pull/86#issuecomment-1516318694
 
* An error is raised when adding the XBlock:
```
Traceback (most recent call last):
edx.devstack.studio               |   File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 337, in get_preview_fragment
edx.devstack.studio               |     fragment = block.render(preview_view, context)
edx.devstack.studio               |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/xblock/core.py", line 198, in render
edx.devstack.studio               |     return self.runtime.render(self, view, context)
edx.devstack.studio               |   File "/edx/app/edxapp/edx-platform/xmodule/x_module.py", line 1781, in render
edx.devstack.studio               |     return self.__getattr__('render')(block, view_name, context)  # pylint: disable=unnecessary-dunder-call
edx.devstack.studio               |   File "/edx/app/edxapp/edx-platform/xmodule/x_module.py", line 1018, in render
edx.devstack.studio               |     return super().render(block, view_name, context=context)
edx.devstack.studio               |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/xblock/runtime.py", line 847, in render
edx.devstack.studio               |     frag = view_fn(context)
edx.devstack.studio               |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/animation/animation.py", line 80, in student_view
edx.devstack.studio               |     inner_width=self.width-20,
edx.devstack.studio               | TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by shadinaif** [comment]
XBlock will be deprecated https://github.com/openedx/AnimationXBlock/pull/86#issuecomment-1539754024
